version: '3.8'

services:
  # Backend API server
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # Expose API port
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6380  # Match the port used in the main app
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - KEY_PREFIX=${KEY_PREFIX:-trading:}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-stream-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend web application
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"  # Expose web UI port
    depends_on:
      - backend
    networks:
      - ai-stream-network
    environment:
      - PUBLIC_API_URL=http://localhost:8000

networks:
  ai-stream-network:
    driver: bridge