# config.sample.yaml

# General settings
interval_minutes: 10  # How often to run the trading cycle
ai_provider: "anthropic"  # One of: anthropic, gemini, openai

# Stop Loss Management Configuration
stop_loss:
  timeframe: "4H"
  initial_multiplier: 1.5
  in_profit_multiplier: 2.0

# Trading parameters per symbol
symbols:
  BTCUSDT:
    budget: 200
    leverage: 5

  SOLUSDT:
    budget: 200
    leverage: 5