timeframes:
  1m:
    interval: "1"
    candles: 720
    minutes: 1
    views:
      - name: "price"
        title: "Price Action (1m)"
        height_ratio: 1.0
        indicators:
          - type: "volume"
            subplot: true
      - name: "momentum"
        title: "Momentum (1m)"
        height_ratio: 0.8
        indicators:
          - type: "rsi"
            parameters:
              period: 7
              overbought: 80
              oversold: 20
            subplot: true

  5m:
    interval: "5"
    candles: 576
    minutes: 5
    views:
      - name: "price"
        title: "Price Action (5m)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 8
            overlay: true
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "volume"
            subplot: true

  15m:
    interval: "15"
    candles: 672
    minutes: 15
    views:
      - name: "price"
        title: "Price Action (15m)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true
          - type: "volume"
            subplot: true
      - name: "momentum"
        title: "Momentum (15m)"
        height_ratio: 0.8
        indicators:
          - type: "rsi"
            parameters:
              period: 14
            subplot: true

  1H:
    interval: "60"
    candles: 336
    minutes: 60
    views:
      - name: "trend"
        title: "Trend Analysis (1H)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 55
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true
      - name: "momentum"
        title: "Momentum Analysis (1H)"
        height_ratio: 0.8
        indicators:
          - type: "macd"
            subplot: true
          - type: "volume"
            subplot: true

  4H:
    interval: "240"
    candles: 180
    minutes: 240
    views:
      - name: "trend"
        title: "Trend Analysis (4H)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 55
            overlay: true
          - type: "ema"
            parameters:
              period: 200
            overlay: true
      - name: "momentum"
        title: "Momentum Analysis (4H)"
        height_ratio: 0.8
        indicators:
          - type: "macd"
            subplot: true
          - type: "rsi"
            parameters:
              period: 14
            subplot: true

  1D:
    interval: "D"
    candles: 180
    minutes: 1440
    views:
      - name: "trend"
        title: "Long Term Trend (1D)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 55
            overlay: true
          - type: "ema"
            parameters:
              period: 200
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true
      - name: "momentum"
        title: "Long Term Momentum (1D)"
        height_ratio: 0.8
        indicators:
          - type: "macd"
            subplot: true

  1W:
    interval: "W"
    candles: 53
    minutes: 10080
    views:
      - name: "trend"
        title: "Major Trend (1W)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 55
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true

# Temporary mapping for backward compatibility
strategy_timeframes:
  "Short (1-7d)": ["1m", "5m", "15m", "1H", "4H"]
  "Medium (1-4w)": ["1H", "4H", "1D"]
  "Long (1-6m)": ["4H", "1D", "1W"]