timeframes:
  1W:
    interval: "W"
    candles: 53
    minutes: 10080  # 7 * 24 * 60
    indicators:
      - type: "ema"
        parameters:
          period: 200
        overlay: true
      - type: "bollinger"
        overlay: true
      - type: "macd"
        subplot: true
      
  1D:
    interval: "D"
    candles: 180
    minutes: 1440  # 24 * 60
    indicators:
      - type: "ema"
        parameters:
          period: 50
        overlay: true
      - type: "ema"
        parameters:
          period: 200
        overlay: true
      - type: "macd"
        subplot: true
      - type: "volume"
        subplot: true

  4H:
    interval: "240"
    candles: 180
    minutes: 240  # 4 * 60
    indicators:
      - type: "ema"
        parameters:
          period: 20
        overlay: true
      - type: "ema"
        parameters:
          period: 50
        overlay: true
      - type: "rsi"
        subplot: true
      - type: "volume"
        subplot: true

  1H:
    interval: "60"
    candles: 336
    minutes: 60
    indicators:
      - type: "ema"
        parameters:
          period: 20
        overlay: true
      - type: "volume"
        subplot: true
      - type: "rsi"
        subplot: true

  15m:
    interval: "15"
    candles: 672
    minutes: 15
    indicators:
      - type: "rsi"
        parameters:
          period: 14
        subplot: true
      - type: "volume"
        subplot: true

  1m:
    interval: "1"
    candles: 720
    minutes: 1
    indicators:
      - type: "rsi"
        parameters:
          period: 7
        subplot: true
      - type: "volume"
        subplot: true

# Temporary mapping for backward compatibility
strategy_timeframes:
  "Short (1-7d)": ["1m", "15m", "1H", "4H"]
  "Medium (1-4w)": ["1H", "4H", "1D"]
  "Long (1-6m)": ["4H", "1D", "1W"]