timeframes:
  5m:
    interval: "5"
    candles: 576
    minutes: 5
    views:
      - name: "price"
        title: "Price Action (5m)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 100
            overlay: true
          - type: "volume"
            subplot: true

  15m:
    interval: "15"
    candles: 672
    minutes: 15
    views:
      - name: "price"
        title: "Price Action (15m)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 100
            overlay: true
          - type: "volume"
            subplot: true

  1H:
    interval: "60"
    candles: 336
    minutes: 60
    views:
      - name: "trend"
        title: "Trend Analysis (1H)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 100
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true
      - name: "momentum"
        title: "Momentum Analysis (1H)"
        height_ratio: 0.8
        indicators:
          - type: "macd"
            subplot: true
          - type: "volume"
            subplot: true

  4H:
    interval: "240"
    candles: 180
    minutes: 240
    views:
      - name: "trend"
        title: "Trend Analysis (4H)"
        height_ratio: 1.0
        indicators:
          - type: "ema"
            parameters:
              period: 21
            overlay: true
          - type: "ema"
            parameters:
              period: 100
            overlay: true
          - type: "bollinger"
            parameters:
              period: 20
              std_dev: 2.0
            overlay: true
      - name: "momentum"
        title: "Momentum Analysis (4H)"
        height_ratio: 0.8
        indicators:
          - type: "macd"
            subplot: true
          - type: "rsi"
            parameters:
              period: 14
            subplot: true

  
